@url=http://localhost:3000
###
GET {{url}}/users

###
POST  {{url}}/users
content-type: application/json

{
    "name": ""
}
###
PUT  {{url}}/users/2
content-type: application/json

{
    "name": ""
}

###
DELETE {{url}}/users/5
###
POST  {{url}}/recipes
content-type: application/json

{
    "title":"telur gulung",
    "descriptions": "telur",
    "photo": "http://localhost",
    "users_id":4
}
######################## login regris jwt#############################
###

GET http://localhost:3000/users

###
POST  {{url}}/auth/register
content-type: application/json

{
    "email":"nly44474@nezid.com",
    "name":"nezid",
    "password":"123"
}

###
POST  {{url}}/auth/login
content-type: application/json

{
    "email":"aqk23510@zslsz.com",
    "password":"123"
}

###
GET  {{url}}/recipes
Authorization: 12312312313

###
GET  {{url}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgzMGIxODQzLWFhOWUtNDc3MC1iMGE3LWE3MTA1ZWUxYjRhNiIsImVtYWlsIjoiYXFrMjM1MTBAenNsc3ouY29tIiwiZnVsbG5hbWUiOiJ6c2xzeiIsInBob3RvIjpudWxsLCJ2ZXJpZiI6MSwib3RwIjoiMjUzMTY4IiwiY3JlYXRlX2F0IjoiMjAyMy0wMi0yNVQyMjoyNzoxOC4wMzVaIiwiaWF0IjoxNjc3Mzg5MzI4LCJleHAiOjE2Nzg3MDMzMjh9.eRSoq1pPRDZd8fejUQObHpOYdHy9zsLjxe3I1xRLel4


###
GET  {{url}}/recipes/my-recipe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgzMGIxODQzLWFhOWUtNDc3MC1iMGE3LWE3MTA1ZWUxYjRhNiIsImVtYWlsIjoiYXFrMjM1MTBAenNsc3ouY29tIiwiZnVsbG5hbWUiOiJ6c2xzeiIsInBob3RvIjpudWxsLCJ2ZXJpZiI6MSwib3RwIjoiMjUzMTY4IiwiY3JlYXRlX2F0IjoiMjAyMy0wMi0yNVQyMjoyNzoxOC4wMzVaIiwiaWF0IjoxNjc3Mzg5MzI4LCJleHAiOjE2Nzg3MDMzMjh9.eRSoq1pPRDZd8fejUQObHpOYdHy9zsLjxe3I1xRLel4

###
POST  {{url}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4Y2Q3ZjVjLWIxNTYtNDI4Yi04ODU2LWI5MWQ1NjdmYjI4YSIsImVtYWlsIjoicmV2b2ZhcmlzQHlhaG9vLmlkIiwiZnVsbG5hbWUiOiJyZXZvZmFyaXMiLCJwaG90byI6bnVsbCwidmVyaWYiOjAsIm90cCI6bnVsbCwiY3JlYXRlX2F0IjpudWxsLCJpYXQiOjE2NzcyNTE0MTgsImV4cCI6MTY3ODU2NTQxOH0.YDVv9oyQoKqBJekgpY5vfq13yQQrOGD51l-nYleYk0M
content-type: application/json

{
    "title":"telur puyuh",
    "descriptions": "telur dan bumbu rahasia",
    "photo": "http://localhost",
    "category_id":"2"
}

###
GET https://res.cloudinary.com/drlwo9tu8/image/upload/v1677384157/food/w3zwvx6qess74pfew2tm.png