@url=http://localhost:3000
###
GET {{url}}/users

###
POST  {{url}}/users
content-type: application/json


{
    "name": ""
}
###
PUT  {{url}}/users/2
content-type: application/json

{
    "name": ""
}

###
DELETE {{url}}/users/5
###
POST  {{url}}/recipes
content-type: application/json

{
    "title":"telur gulung",
    "descriptions": "telur",
    "photo": "http://localhost",
    "users_id":4
}
######################## login regris jwt#############################
###

GET http://localhost:3000/users

###
POST  {{url}}/auth/register
content-type: application/json

{
    "email":"jmn54796@nezid.com",
    "name":"nezid",
    "password":"123"
}

###
POST  {{url}}/auth/login
content-type: application/json

{
    "email":"aqk23510@zslsz.com",
    "password":"123"
}

###
GET  {{url}}/recipes
Authorization: 12312312313

###
GET  {{url}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwOGE1NmQyLWZlNWMtNDFlZi1hYmIwLWY5MmMxYzQ5OWQyMiIsImVtYWlsIjoidXJ1MTE4MDZAbmV6aWQuY29tIiwiZnVsbG5hbWUiOiJuZXppZCIsInBob3RvIjpudWxsLCJ2ZXJpZiI6MSwib3RwIjoiNjQ3MjIxIiwiY3JlYXRlX2F0IjoiMjAyMy0wMi0yNlQwMTo1Nzo1OC44NDZaIiwiaWF0IjoxNjc3NDAyNzMwLCJleHAiOjE2Nzg3MTY3MzB9.ladotrWrrwEvGQeQd94VQzjPnuPL8vqAGUR4h-ppnBw

###
GET  {{url}}/recipes/my-recipe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljNzEyYmQzLTMzOWQtNDcwNi1hY2I2LTI4NzY5ZjdmNTRhMSIsImVtYWlsIjoicHNkNzM0ODhAenNsc3ouY29tIiwiZnVsbG5hbWUiOiJ6c2xzeiIsInBob3RvIjpudWxsLCJ2ZXJpZiI6MSwib3RwIjoiMzE3ODYyIiwiY3JlYXRlX2F0IjoiMjAyMy0wMi0yNVQwMzo1NjoyMS41NDlaIiwiaWF0IjoxNjc3Mzg0NDg2LCJleHAiOjE2Nzg2OTg0ODZ9.4EkjBy1ZqMRPDzXsL98_mqpgpdc-zw6XxuSuJ1VGvBU

###
POST  {{url}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgzMGIxODQzLWFhOWUtNDc3MC1iMGE3LWE3MTA1ZWUxYjRhNiIsImVtYWlsIjoiYXFrMjM1MTBAenNsc3ouY29tIiwiZnVsbG5hbWUiOiJ6c2xzeiIsInBob3RvIjpudWxsLCJ2ZXJpZiI6MSwib3RwIjoiMjUzMTY4IiwiY3JlYXRlX2F0IjoiMjAyMy0wMi0yNVQyMjoyNzoxOC4wMzVaIiwiaWF0IjoxNjc3Mzk5NjkxLCJleHAiOjE2Nzg3MTM2OTF9.2aK3jdNvv5UqU6Frs0VqaJYrF93482_v_6U6qHUeNZw
content-type: application/json

{
    "title":"telur puyuh",
    "descriptions": "telur dan bumbu rahasia",
    "photo": "http://localhost",
    "category_id":"2"
}

###
GET https://res.cloudinary.com/drlwo9tu8/image/upload/v1677384157/food/w3zwvx6qess74pfew2tm.png

###
DELETE   {{url}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwOGE1NmQyLWZlNWMtNDFlZi1hYmIwLWY5MmMxYzQ5OWQyMiIsImVtYWlsIjoidXJ1MTE4MDZAbmV6aWQuY29tIiwiZnVsbG5hbWUiOiJuZXppZCIsInBob3RvIjpudWxsLCJ2ZXJpZiI6MSwib3RwIjoiNjQ3MjIxIiwiY3JlYXRlX2F0IjoiMjAyMy0wMi0yNlQwMTo1Nzo1OC44NDZaIiwiaWF0IjoxNjc3NDAyNzMwLCJleHAiOjE2Nzg3MTY3MzB9.ladotrWrrwEvGQeQd94VQzjPnuPL8vqAGUR4h-ppnBw

